// <auto-generated />
using DABHandIn4.SmartGridInfoRestApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DABHandIn4.SmartGridInfoRestApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DABHandIn4.SmartGridInfoRestApi.Entities.Adresse", b =>
                {
                    b.Property<long>("AdresseId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bynavn");

                    b.Property<string>("Husnummer");

                    b.Property<string>("Postnummer");

                    b.Property<long>("SmartEnhedId");

                    b.Property<string>("Vejnavn");

                    b.HasKey("AdresseId");

                    b.HasIndex("SmartEnhedId");

                    b.ToTable("Adresse");
                });

            modelBuilder.Entity("DABHandIn4.SmartGridInfoRestApi.Entities.Elkilde", b =>
                {
                    b.Property<long>("ElkildeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type");

                    b.HasKey("ElkildeId");

                    b.ToTable("Elkilde");
                });

            modelBuilder.Entity("DABHandIn4.SmartGridInfoRestApi.Entities.Har", b =>
                {
                    b.Property<long>("SmartEnhedId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Antal");

                    b.Property<long>("ElkildeId");

                    b.Property<long>("SmartEnhedId1");

                    b.HasKey("SmartEnhedId");

                    b.HasIndex("ElkildeId");

                    b.HasIndex("SmartEnhedId1");

                    b.ToTable("Har");
                });

            modelBuilder.Entity("DABHandIn4.SmartGridInfoRestApi.Entities.SmartEnhed", b =>
                {
                    b.Property<long>("SmartEnhedId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ProsumerId");

                    b.Property<long>("SmartMeterId");

                    b.Property<long>("TypeId");

                    b.HasKey("SmartEnhedId");

                    b.HasIndex("SmartMeterId");

                    b.HasIndex("TypeId");

                    b.ToTable("SmartEnhed");
                });

            modelBuilder.Entity("DABHandIn4.SmartGridInfoRestApi.Entities.SmartMeter", b =>
                {
                    b.Property<long>("SmartMeterId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("SmartMeterId");

                    b.ToTable("SmartMeter");
                });

            modelBuilder.Entity("DABHandIn4.SmartGridInfoRestApi.Entities.Type", b =>
                {
                    b.Property<long>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TypeNavn");

                    b.HasKey("TypeId");

                    b.ToTable("Type");
                });

            modelBuilder.Entity("DABHandIn4.SmartGridInfoRestApi.Entities.Adresse", b =>
                {
                    b.HasOne("DABHandIn4.SmartGridInfoRestApi.Entities.SmartEnhed", "SmartEnhed")
                        .WithMany("Adresses")
                        .HasForeignKey("SmartEnhedId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DABHandIn4.SmartGridInfoRestApi.Entities.Har", b =>
                {
                    b.HasOne("DABHandIn4.SmartGridInfoRestApi.Entities.Elkilde", "Elkilde")
                        .WithMany("Hars")
                        .HasForeignKey("ElkildeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DABHandIn4.SmartGridInfoRestApi.Entities.SmartEnhed", "SmartEnhed")
                        .WithMany("Hars")
                        .HasForeignKey("SmartEnhedId1")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DABHandIn4.SmartGridInfoRestApi.Entities.SmartEnhed", b =>
                {
                    b.HasOne("DABHandIn4.SmartGridInfoRestApi.Entities.SmartMeter", "SmartMeter")
                        .WithMany("SmartEnheds")
                        .HasForeignKey("SmartMeterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DABHandIn4.SmartGridInfoRestApi.Entities.Type", "Type")
                        .WithMany("SmartEnheds")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
