// <auto-generated />
using DABHandIn4.ProsumerInfoRestApi.Presistences;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DABHandIn4.ProsumerInfoRestApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DABHandIn4.ProsumerInfoRestApi.Entities.Forbrug", b =>
                {
                    b.Property<long>("ForbrugId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AarligkWh");

                    b.Property<DateTime>("Aarstal");

                    b.Property<int?>("Kvartal1kWh");

                    b.Property<int?>("Kvartal2kWh");

                    b.Property<int?>("Kvartal3kWh");

                    b.Property<int?>("Kvartal4kWh");

                    b.Property<long>("ProsumerId");

                    b.HasKey("ForbrugId");

                    b.HasIndex("ProsumerId");

                    b.ToTable("Forbrug");
                });

            modelBuilder.Entity("DABHandIn4.ProsumerInfoRestApi.Entities.PersonAntal", b =>
                {
                    b.Property<long>("PersonAntalId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AntalVoksne");

                    b.Property<long?>("ProsumerId");

                    b.HasKey("PersonAntalId");

                    b.HasIndex("ProsumerId");

                    b.ToTable("PersonAntal");
                });

            modelBuilder.Entity("DABHandIn4.ProsumerInfoRestApi.Entities.Prosumer", b =>
                {
                    b.Property<long>("ProsumerId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("SmartEnhedId");

                    b.HasKey("ProsumerId");

                    b.ToTable("Prosumer");
                });

            modelBuilder.Entity("DABHandIn4.ProsumerInfoRestApi.Entities.Forbrug", b =>
                {
                    b.HasOne("DABHandIn4.ProsumerInfoRestApi.Entities.Prosumer", "Prosumer")
                        .WithMany("Forbrugs")
                        .HasForeignKey("ProsumerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DABHandIn4.ProsumerInfoRestApi.Entities.PersonAntal", b =>
                {
                    b.HasOne("DABHandIn4.ProsumerInfoRestApi.Entities.Prosumer", "Prosumer")
                        .WithMany("PersonAntals")
                        .HasForeignKey("ProsumerId");
                });
#pragma warning restore 612, 618
        }
    }
}
