//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DABHandIn4.EFModelDatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresse
    {
        public long AdresseId { get; set; }
        public string Vejnavn { get; set; }
        public string Husnummer { get; set; }
        public string Postnummer { get; set; }
        public string Bynavn { get; set; }
        public long SmartEnhedId { get; set; }
    
        public virtual SmartEnhed SmartEnhed { get; set; }
    }
}
