//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DABHandIn4.EFModelDatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Har
    {
        public long SmartEnhedId { get; set; }
        public long ElkildeId { get; set; }
        public int Antal { get; set; }
    
        public virtual Elkilde Elkilde { get; set; }
        public virtual SmartEnhed SmartEnhed { get; set; }
    }
}
