//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DABHandIn4.EFModelDatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonAntal
    {
        public long PersonAntalId { get; set; }
        public int AntalVoksne { get; set; }
        public Nullable<long> ProsumerId { get; set; }
    
        public virtual Prosumer Prosumer { get; set; }
    }
}
