//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DABHandIn4.EFModelDatabaseFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProsumerInfoEntities : DbContext
    {
        public ProsumerInfoEntities()
            : base("name=ProsumerInfoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Forbrug> Forbrugs { get; set; }
        public virtual DbSet<PersonAntal> PersonAntals { get; set; }
        public virtual DbSet<Prosumer> Prosumers { get; set; }
    }
}
