//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DABHandIn4.EFModelDatabaseFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DAB4Entities : DbContext
    {
        public DAB4Entities()
            : base("name=DAB4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adresse> Adresses { get; set; }
        public virtual DbSet<Elkilde> Elkildes { get; set; }
        public virtual DbSet<Har> Hars { get; set; }
        public virtual DbSet<SmartEnhed> SmartEnheds { get; set; }
        public virtual DbSet<SmartMeter> SmartMeters { get; set; }
        public virtual DbSet<Type> Types { get; set; }
    }
}
