//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DABHandIn4.EFModelDatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmartEnhed
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SmartEnhed()
        {
            this.Adresses = new HashSet<Adresse>();
            this.Hars = new HashSet<Har>();
        }
    
        public long SmartEnhedId { get; set; }
        public long ProsumerId { get; set; }
        public long SmartMeterId { get; set; }
        public long TypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adresse> Adresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Har> Hars { get; set; }
        public virtual SmartMeter SmartMeter { get; set; }
        public virtual Type Type { get; set; }
    }
}
